export const recentPropertyData = [
  {
    type: "rent",
    img1: "/prt-1.png",
    img2: "/prt-2.png",
    img3: "/prt-3.png",
    tag: "trending",
    price: "Rs. 10,000",
    name: "Goldfinch Real Property",
    address: "210 Zirak Road, Canada",
    bed: 3,
    bathroom: 2,
    area: "2200 Sft",
  },
  {
    type: "rent",
    img1: "/prt-2.png",
    img2: "/prt-4.png",
    img3: "/prt-5.png",
    tag: "trending",
    price: "Rs. 14,000",
    name: "Goldfinch Real Property",
    address: "210 Zirak Road, Canada",
    bed: 3,
    bathroom: 2,
    area: "2200 Sft",
  },
  {
    type: "rent",
    img1: "/prt-3.png",
    img2: "/prt-6.png",
    img3: "/prt-7.png",
    tag: "trending",
    price: "Rs. 18,000",
    name: "Goldfinch Real Property",
    address: "210 Zirak Road, Canada",
    bed: 3,
    bathroom: 2,
    area: "2200 Sft",
  },
  {
    type: "rent",
    img1: "/prt-4.png",
    img2: "/prt-8.png",
    img3: "/prt-9.png",
    tag: "trending",
    price: "Rs. 1,00,000",
    name: "Goldfinch Real Property",
    address: "210 Zirak Road, Canada",
    bed: 3,
    bathroom: 2,
    area: "2200 Sft",
  },
  {
    type: "rent",
    img1: "/prt-5.png",
    img2: "/prt-10.png",
    img3: "/prt-11.png",
    tag: "trending",
    price: "Rs. 1,00,000",
    name: "Goldfinch Real Property",
    address: "210 Zirak Road, Canada",
    bed: 3,
    bathroom: 2,
    area: "2200 Sft",
  },
  {
    type: "rent",
    img1: "/prt-6.png",
    img2: "/prt-12.png",
    img3: "/prt-13.png",
    tag: "trending",
    price: "Rs. 1,00,000",
    name: "Goldfinch Real Property",
    address: "210 Zirak Road, Canada",
    bed: 3,
    bathroom: 2,
    area: "2200 Sft",
  },
  {
    type: "rent",
    img1: "/prt-7.png",
    img2: "/prt-14.png",
    img3: "/prt-15.png",
    tag: "trending",
    price: "Rs. 1,00,000",
    name: "Goldfinch Real Property",
    address: "210 Zirak Road, Canada",
    bed: 3,
    bathroom: 2,
    area: "2200 Sft",
  },
  {
    type: "rent",
    img1: "/prt-8.png",
    img2: "/prt-1.png",
    img3: "/prt-2.png",
    tag: "trending",
    price: "Rs. 1,00,000",
    name: "Goldfinch Real Property",
    address: "210 Zirak Road, Canada",
    bed: 3,
    bathroom: 2,
    area: "2200 Sft",
  },
];
