import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import RecentProperties from "@/components/recentProperties";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>RealState</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <main className={`${styles.main} ${inter.className}`}>
      </main> */}
      <RecentProperties />
    </>
  );
}
