import Head from "next/head";
import Hero from "@/components/hero/hero";
import { Inter } from "next/font/google";
import RecentProperties from "@/components/recentProperty/recentProperties";
import ServicesProvide from "@/components/servicesProvide";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>RealState</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero />
      <RecentProperties />
      <ServicesProvide />
    </>
  );
}
